# Generated by Django 5.1.5 on 2025-01-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="state_file",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Документ отклонен"),
                    (1, "Документ принят"),
                    (2, "Докумен на проверке"),
                ],
                default=2,
                help_text="Состояние документа",
                verbose_name="Состояние документа",
            ),
        ),
    ]
